In [ ]:
import numpy as np 

In [ ]:
#an array with 8 elements is created
one_dimensional_array = np.array([1.5, 2.6, 3.7, 4.8, 6.9, 7.4, 8.2, 9.3])
print(one_dimensional_array)

[1.5 2.6 3.7 4.8 6.9 7.4 8.2 9.3]


In [ ]:
#a matrix of 3x2 is created
two_dimensional_array = np.array([[1, 2], [3, 4], [5, 6]])
print(two_dimensional_array)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#the array is filled with numbers dec 7 to 14
sequence_of_integers = np.arange(7, 14)
print(sequence_of_integers)

[ 7  8  9 10 11 12 13]


In [ ]:
#a random sequence of 5 elements dec 30 to 80 is generated
random_integers_between_30_and_80 = np.random.randint(low=29, high=81, size=(5))
print(random_integers_between_30_and_80)

[38 54 50 46 57]


In [ ]:
#an array of 6 float elements is randomly generated between dec.0 and 1.0
random_floats_between_0_and_1 = np.random.random([6])
print(random_floats_between_0_and_1)

[0.08228643 0.61741622 0.21906986 0.63555034 0.1988785  0.16942525]


In [ ]:
#2.0 is added to the value of each element in the array
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

[2.08228643 2.61741622 2.21906986 2.63555034 2.1988785  2.16942525]


In [ ]:
#the value of each element in the array is multiplied by 3.0
random_integers_between_100_and_300 = random_integers_between_30_and_80 * 3
print(random_integers_between_100_and_300)

[114 162 150 138 171]


In [ ]:
#An int array dec 6 to 20 (inclusive) is assigned to a property called a NumPy array.
#A NumPy array named Tag is assigned 15 values
feature = np.arange(6, 21)
print(feature)
label = (feature * 3) + 4
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


In [ ]:
#each value assigned to dec label is changed by adding a different random float value between -2 and +2
noise = (np.random.random([15]) * 4) - 2
print(noise)
label = label + noise 
print(label)

[ 0.74801615  0.34110674 -0.25355422  1.86648053 -1.7178096  -1.48426161
  1.42446379 -1.76083569 -1.87356197  1.23393403  0.64686356  1.76359895
 -0.37732134  1.29057127  1.31921738]
[22.74801615 25.34110674 27.74644578 32.86648053 32.2821904  35.51573839
 41.42446379 41.23916431 44.12643803 50.23393403 52.64686356 56.76359895
 57.62267866 62.29057127 65.31921738]
